### ISSUE TITLE
Dependency sync-is-private-host@0.1.2 restricts engines to node 6 and npm 3

### ISSUE THREAD

**Issue by bastianandre-myenso** [erkstruwe/tiny.pictures-sdk-js#35]
The dependency sync-is-private-host@0.1.2 restricts engines to node 6 and npm 3
```log
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'sync-is-private-host@0.1.2',
npm WARN EBADENGINE   required: { node: '^6.9.5', npm: '^3.10.10' },
npm WARN EBADENGINE   current: { node: 'v18.12.1', npm: '8.19.2' }
npm WARN EBADENGINE }
```

This constrain is removed in sync-is-private-host@1.0.0, but **tiny.pictures-js** still references the old version with ^0.1.2.
```json
"engines": {
  "node": "^6.9.5",
  "npm": "^3.10.10"
 }
```
This causes a EBADENGINE error in more up-to-date setups.
As a peer dependency npm wont automatically update that package on module resolution unless explicitly listed in our own package.json with a newer version. 
Could you bump the dependency version in question?

**Comment by erkstruwe** [comment]
Thanks for raising this issue. Commit d0ed8bdeebdafa9cb27b479709052372d3dbea64 fixes this issue. Released on npm as v4.2.7.
